### ISSUE TITLE
Added initial northwind project

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/dbt-airflow-northwind#1]
Task:https://n-abledev.atlassian.net/browse/DA-2096?atlOrigin=eyJpIjoiZmU2ZmFjOTVlNDA1NDQwOTkwYzhlOWQ0MDlkZDUwOTkiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
- [x] Remove unwanted files from the branch 
- [x] Update README.md file 
- [x] add docker-compose for airflow and dags dir in root

**Comment by koshitha-nable** [comment]
removed unwanted files and updated readme file

**Comment by piranavan-nable** [comment]
Merge pull request #2 from koshitha-nable/ka/feature/001/add_initial_project
